### PR TITLE
Allow null as eventCallback type

### LINKED ISSUE #422: [Typescript] eventCallback does not allow 'null'
According to documentation of `eventCallback` https://greensock.com/docs/v3/GSAP/Timeline/eventCallback() it should allow `null` as callback value to delete associated event, however types do not allow this and only function is allowed.

### PR DESCRIPTION
**Pull request by IljaDaderko**
closes #422

### CODE REVIEW

**Comment by jackdoyle** [comment]
Thanks for pointing this out. We'll get it resolved in the next release.

**Review by Ridvanovskyy — APPROVED** [review]

**Comment by jackdoyle** [comment]
Is there a reason you did "void | null" instead of just "any"?

**Comment by OSUblake** [comment]
Using `any` would allow you to use the return in an unchecked way.
https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#return-types-of-callbacks

**Comment by jackdoyle** [comment]
> Using `any` would allow you to use the return in an unchecked way.
> https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#return-types-of-callbacks

@OSUblake I see, but then if you happen to use a callback that returns a value of any kind, might that cause problems? In other words, are TypeScript users forced to only use callbacks that don't return a value?

**Comment by OSUblake** [comment]
Callbacks aren't supposed to return a value because they usually aren't synchronous. If a value is needed from a callback, then it would be passed in the function.

**Comment by jackdoyle** [comment]
> Callbacks aren't supposed to return a value because they usually aren't synchronous. If a value is needed from a callback, then it would be passed in the function.

Right, that's what we typically see. However, someone may have a function that's used for other purposes too (so maybe it returns a value for those other uses), AND they want to call it at the end of an animation, so they pass it in as the onComplete. If we set up the TypeScript definitions to only allow void, wouldn't it throw an error in this scenario? So users would be forced to wrap it in another function that doesn't return anything? Maybe I'm misunderstanding.

**Comment by OSUblake** [comment]
> However, someone may have a function that's used for other purposes too (so maybe it returns a value for those other uses),

I see, but I think that should be up to the user to cast i.e.
```ts
foo(myFunction as () => void);
```

**Comment by jackdoyle** [comment]
> I see, but I think in cases like that, it should be up to the user to cast i.e.
> 
> ```ts
> foo(myFunction as () => void);
> ```

The reason given in that link was: _"Using void is safer because it prevents you from accidentally using the return value of x in an unchecked way"_ but why would that be relevant for GSAP? It's not like we use the result of the callback internally or anything, so what would the down side be of using "any"? It'd help avoid errors for users who want to reuse that same function for other purposes (where a return value is indeed important). Right?

**Comment by OSUblake** [comment]
> so what would the down side be of using "any"?

You lose type safety. Think about the inverse. Maybe the user wrote the callback incorrectly, and meant to set a value inside of the callback, instead of returning it. Using `any` wouldn't be able to point that out.

It's better to have the user cast the callback if they intend to use a function that returns a value.

And if you change it to `any`, I'm pretty sure you'll get a PR in a couple weeks from someone wanting to change it back to `void` because that's the convention. 😉

I would just change it to `void | null`.

**Comment by jackdoyle** [comment]
> I would just change it to `void | null`.

Alright, you're the TypeScript expert ;)

**Pull request closed without merging**
